# ICU related mortality

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#! UNCOMMENT BELOW IF USING ON COLAB
# Access data using Google BigQuery on Google Colab
# from google.colab import auth
# from google.cloud import bigquery
# auth.authenticate_user()

# Dataset paths
project_id = "composite-drive-359503"   #! CHANGEME
physionet_proj = "physionet-data"
mimic_core = f"{physionet_proj}.mimic_core"
mimic_hosp = f"{physionet_proj}.mimic_hosp"
mimic_icu = f"{physionet_proj}.mimic_icu"
mimic_derived = f"{physionet_proj}.mimic_derived"

# Read data from BigQuery into pandas dataframes.
def run_query(query, project_id=project_id):
    return pd.io.gbq.read_gbq(
        query,
        project_id=project_id,
        dialect='standard')

In [2]:
# Patient death, deathtime < dischtime
patient_death_1 = f"""
--sql
SELECT
    *
FROM
    {mimic_core}.admissions AS admissions
WHERE
    admissions.deathtime < admissions.dischtime
ORDER BY
    subject_id, hadm_id
"""

In [3]:
run_query(patient_death_1)

/opt/homebrew/Caskroom/miniconda/base/envs/GBQ/lib/python3.10/site-packages/google/auth/_default.py:81: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,marital_status,ethnicity,edregtime,edouttime,hospital_expire_flag
0,10285188,21275116,2131-12-10 16:08:00,2131-12-15 21:08:00,2131-12-15 01:38:00,DIRECT EMER.,PHYSICIAN REFERRAL,DIED,Medicaid,ENGLISH,SINGLE,WHITE,NaT,NaT,1
1,10398726,28426324,2171-04-24 18:17:00,2171-04-24 18:23:00,2171-04-24 10:39:00,EU OBSERVATION,EMERGENCY ROOM,None,Medicaid,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,2171-04-24 11:34:00,2171-04-25 00:48:00,1
2,10458469,26080103,2122-08-25 21:54:00,2122-08-27 21:45:00,2122-08-27 00:50:00,EU OBSERVATION,EMERGENCY ROOM,None,Medicare,ENGLISH,MARRIED,WHITE,2122-08-25 20:14:00,2122-08-26 00:37:00,1
3,10518048,23193885,2187-06-28 16:08:00,2187-06-28 21:30:00,2187-06-28 17:30:00,EW EMER.,EMERGENCY ROOM,DIED,Medicaid,?,SINGLE,HISPANIC/LATINO,2187-06-28 11:54:00,2187-06-28 16:59:00,1
4,10550799,29410506,2161-04-15 19:10:00,2161-05-01 20:00:00,2161-05-01 18:05:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,MARRIED,WHITE,2161-04-15 14:03:00,2161-04-15 21:25:00,1
5,10909143,29830422,2129-04-30 04:33:00,2129-05-08 12:31:00,2129-05-08 10:15:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,WIDOWED,WHITE,2129-04-29 16:27:00,2129-04-30 07:14:00,1
6,11214815,29209324,2142-01-06 21:25:00,2142-01-13 22:34:00,2142-01-13 03:06:00,OBSERVATION ADMIT,EMERGENCY ROOM,DIED,Medicare,ENGLISH,WIDOWED,WHITE,2142-01-06 13:40:00,2142-01-07 02:09:00,1
7,11459649,29496649,2130-08-02 04:58:00,2130-08-03 04:12:00,2130-08-03 01:34:00,EW EMER.,EMERGENCY ROOM,DIED,Other,?,SINGLE,BLACK/AFRICAN AMERICAN,2130-08-02 03:47:00,2130-08-02 05:36:00,1
8,11615006,23379445,2158-10-06 19:26:00,2158-10-06 23:50:00,2158-10-06 00:00:00,DIRECT OBSERVATION,TRANSFER FROM SKILLED NURSING FACILITY,None,Medicare,ENGLISH,MARRIED,ASIAN,2158-10-06 10:04:00,2158-10-06 21:32:00,1
9,11713814,28888207,2159-05-28 02:40:00,2159-06-06 00:40:00,2159-06-06 00:36:00,URGENT,TRANSFER FROM HOSPITAL,DIED,Medicaid,ENGLISH,None,OTHER,NaT,NaT,1
10,11954199,21803732,2139-09-02 15:11:00,2139-09-10 08:00:00,2139-09-10 00:14:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,None,UNKNOWN,2139-09-02 13:29:00,2139-09-02 16:24:00,1
11,12206313,28689333,2148-05-27 23:59:00,2148-06-12 18:15:00,2148-06-12 18:00:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,MARRIED,WHITE,2148-05-27 16:00:00,2148-05-28 01:13:00,1
12,12287535,21494174,2132-06-19 11:16:00,2132-06-21 20:35:00,2132-06-21 00:00:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,WIDOWED,WHITE,2132-06-19 07:55:00,2132-06-19 12:20:00,1
13,12453379,25014610,2135-08-10 12:41:00,2135-08-10 13:43:00,2135-08-10 10:08:00,EW EMER.,PACU,None,Other,ENGLISH,None,WHITE,NaT,NaT,1
14,12486920,20344681,2140-08-06 11:33:00,2140-08-19 04:30:00,2140-08-19 03:00:00,DIRECT EMER.,CLINIC REFERRAL,DIED,Medicare,ENGLISH,SINGLE,HISPANIC/LATINO,NaT,NaT,1
15,12590289,24483581,2131-03-22 00:55:00,2131-03-24 06:35:00,2131-03-24 06:33:00,EW EMER.,CLINIC REFERRAL,DIED,Medicare,ENGLISH,WIDOWED,BLACK/AFRICAN AMERICAN,2131-03-21 22:14:00,2131-03-22 01:52:00,1
16,12641980,28255255,2167-10-26 13:24:00,2167-10-28 06:10:00,2167-10-28 03:19:00,URGENT,TRANSFER FROM SKILLED NURSING FACILITY,DIED,Medicare,ENGLISH,SINGLE,WHITE,2167-10-26 11:37:00,2167-10-26 14:30:00,1
17,12649413,29630195,2187-09-23 01:15:00,2187-09-24 19:38:00,2187-09-24 19:30:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,None,UNKNOWN,2187-09-22 20:39:00,2187-09-23 02:03:00,1
18,12921133,28654657,2134-10-30 14:45:00,2134-10-30 20:34:00,2134-10-30 00:00:00,EU OBSERVATION,EMERGENCY ROOM,None,Medicare,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,2134-10-30 12:09:00,2134-10-30 13:40:00,1
19,13013332,29359746,2170-10-20 15:59:00,2170-10-20 20:10:00,2170-10-20 06:04:00,EU OBSERVATION,EMERGENCY ROOM,None,Medicare,ENGLISH,MARRIED,WHITE,2170-10-20 12:57:00,2170-10-20 17:08:00,1
20,13155340,21981184,2179-02-14 03:00:00,2179-02-14 18:30:00,2179-02-14 18:02:00,URGENT,TRANSFER FROM HOSPITAL,DIED,Medicare,?,WIDOWED,BLACK/AFRICAN AMERICAN,NaT,NaT,1
21,13207574,27590526,2180-02-28 01:59:00,2180-03-03 03:29:00,2180-03-03 02:09:00,EW EMER.,WALK-IN/SELF REFERRAL,DIED,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,2180-02-27 20:25:00,2180-02-28 03:17:00,1
22,13655592,27569643,2140-02-26 20:52:00,2140-03-01 04:00:00,2140-03-01 02:24:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,SINGLE,WHITE,2140-02-26 15:55:00,2140-02-26 22:53:00,1
23,13678157,27816922,2144-07-19 17:19:00,2144-07-21 21:45:00,2144-07-21 21:41:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,MARRIED,OTHER,2144-07-19 11:55:00,2144-07-19 20:19:00,1
24,14122032,27285527,2121-07-26 18:31:00,2121-07-26 22:50:00,2121-07-26 13:10:00,EU OBSERVATION,EMERGENCY ROOM,None,Other,ENGLISH,MARRIED,WHITE,2121-07-26 15:16:00,2121-07-26 20:55:00,1
25,14441506,28327879,2174-03-27 05:57:00,2174-03-27 20:57:00,2174-03-27 14:34:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,None,UNKNOWN,2174-03-27 04:00:00,2174-03-27 06:45:00,1
26,14534270,25562359,2150-12-06 01:35:00,2150-12-08 22:55:00,2150-12-08 04:17:00,EU OBSERVATION,EMERGENCY ROOM,None,Other,ENGLISH,SINGLE,HISPANIC/LATINO,2150-12-05 21:52:00,2150-12-06 02:59:00,1
27,14659176,21162467,2174-06-15 22:01:00,2174-06-15 14:50:00,2174-06-15 00:03:00,ELECTIVE,None,DIED,Medicaid,ENGLISH,None,OTHER,NaT,NaT,1
28,14677586,28059300,2206-03-19 16:15:00,2206-03-21 03:49:00,2206-03-21 02:04:00,SURGICAL SAME DAY ADMISSION,PHYSICIAN REFERRAL,DIED,Other,ENGLISH,WIDOWED,WHITE,NaT,NaT,1
29,15166183,24702229,2147-05-26 15:30:00,2147-05-28 22:00:00,2147-05-28 07:00:00,EU OBSERVATION,EMERGENCY ROOM,None,Medicare,?,WIDOWED,WHITE,2147-05-26 10:02:00,2147-05-26 16:54:00,1
30,15525846,27861206,2165-07-01 19:30:00,2165-07-01 23:31:00,2165-07-01 00:00:00,EU OBSERVATION,EMERGENCY ROOM,None,Medicare,ENGLISH,MARRIED,WHITE,2165-07-01 15:46:00,2165-07-01 21:34:00,1
31,15573925,27811225,2136-04-01 16:40:00,2136-04-01 19:45:00,2136-04-01 00:01:00,EU OBSERVATION,EMERGENCY ROOM,None,Other,ENGLISH,None,OTHER,2136-04-01 15:58:00,2136-04-01 17:09:00,1
32,15831885,20918234,2119-10-15 16:00:00,2119-11-17 13:46:00,2119-11-17 11:40:00,URGENT,TRANSFER FROM HOSPITAL,DIED,Medicaid,ENGLISH,SINGLE,WHITE,NaT,NaT,1
33,16119710,27019817,2143-12-19 20:19:00,2143-12-30 18:20:00,2143-12-30 17:15:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,MARRIED,WHITE,2143-12-19 15:29:00,2143-12-20 02:31:00,1
34,16533974,24720945,2175-06-02 20:49:00,2175-06-02 23:15:00,2175-06-02 02:42:00,EU OBSERVATION,EMERGENCY ROOM,None,Other,ENGLISH,None,UNKNOWN,2175-06-02 19:26:00,2175-06-02 22:15:00,1
35,16758327,22779550,2181-11-29 23:36:00,2181-12-01 22:40:00,2181-12-01 16:19:00,EW EMER.,EMERGENCY ROOM,DIED,Medicaid,ENGLISH,MARRIED,UNABLE TO OBTAIN,2181-11-29 21:35:00,2181-11-29 22:09:00,1
36,17105370,23214363,2155-09-02 05:15:00,2155-09-07 12:17:00,2155-09-07 08:41:00,URGENT,TRANSFER FROM SKILLED NURSING FACILITY,DIED,Other,ENGLISH,WIDOWED,WHITE,2155-09-02 00:28:00,2155-09-02 06:19:00,1
37,17196501,27250817,2126-06-02 02:49:00,2126-06-07 12:35:00,2126-06-07 09:07:00,EW EMER.,TRANSFER FROM HOSPITAL,DIED,Medicare,ENGLISH,MARRIED,WHITE,2126-06-01 23:15:00,2126-06-02 05:23:00,1
38,17434758,29752616,2133-11-25 19:58:00,2133-11-25 23:36:00,2133-11-25 10:45:00,EU OBSERVATION,EMERGENCY ROOM,None,Medicare,ENGLISH,SINGLE,WHITE,2133-11-25 07:47:00,2133-11-26 02:48:00,1
39,17890530,20300182,2130-01-14 15:29:00,2130-01-17 10:43:00,2130-01-17 09:55:00,OBSERVATION ADMIT,EMERGENCY ROOM,DIED,Other,ENGLISH,DIVORCED,BLACK/AFRICAN AMERICAN,2130-01-14 14:50:00,2130-01-14 16:46:00,1
40,17905362,23955508,2123-05-18 21:27:00,2123-05-30 11:00:00,2123-05-30 10:40:00,URGENT,TRANSFER FROM HOSPITAL,HOME,Medicare,ENGLISH,DIVORCED,WHITE,NaT,NaT,1
41,18266371,28379550,2187-04-09 04:15:00,2187-04-10 12:30:00,2187-04-10 11:55:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,?,MARRIED,WHITE,2187-04-09 03:57:00,2187-04-09 04:46:00,1
42,18301793,20938582,2122-08-26 21:33:00,2122-08-26 22:00:00,2122-08-26 21:58:00,ELECTIVE,None,DIED,Other,ENGLISH,None,WHITE,NaT,NaT,1
43,18541624,26084186,2181-04-18 21:25:00,2181-04-20 19:00:00,2181-04-20 00:41:00,EU OBSERVATION,EMERGENCY ROOM,None,Medicare,?,SINGLE,HISPANIC/LATINO,2181-04-18 19:15:00,2181-04-18 22:27:00,1
44,18873002,23414645,2189-02-09 21:29:00,2189-02-18 03:30:00,2189-02-18 03:15:00,URGENT,TRANSFER FROM HOSPITAL,DIED,Other,?,SINGLE,UNKNOWN,NaT,NaT,1
45,18958515,25534027,2145-12-29 16:43:00,2146-01-08 19:00:00,2146-01-08 18:40:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,DIVORCED,UNKNOWN,2145-12-29 14:47:00,2145-12-29 16:50:00,1
46,18972794,21258620,2174-07-08 01:35:00,2174-07-12 11:00:00,2174-07-12 07:03:00,EW EMER.,INFORMATION NOT AVAILABLE,DIED,Medicare,ENGLISH,WIDOWED,WHITE,2174-07-07 21:37:00,2174-07-08 02:31:00,1
47,19401293,27692995,2136-10-25 17:35:00,2136-10-25 23:48:00,2136-10-25 05:02:00,DIRECT OBSERVATION,TRANSFER FROM SKILLED NURSING FACILITY,None,Other,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,2136-10-25 11:10:00,2136-10-25 19:05:00,1
48,19547124,21742779,2181-01-16 08:54:00,2181-01-16 22:58:00,2181-01-16 03:45:00,EU OBSERVATION,EMERGENCY ROOM,None,Medicare,ENGLISH,MARRIED,UNKNOWN,2181-01-16 05:22:00,2181-01-16 09:35:00,1
49,19618308,21917069,2173-10-18 14:22:00,2173-10-22 20:00:00,2173-10-22 04:23:00,EU OBSERVATION,EMERGENCY ROOM,None,Other,ENGLISH,SINGLE,WHITE,2173-10-18 08:55:00,2173-10-18 15:43:00,1
50,19994505,20026892,2185-11-13 17:22:00,2185-11-17 22:45:00,2185-11-17 00:00:00,EU OBSERVATION,EMERGENCY ROOM,None,Other,?,MARRIED,WHITE,2185-11-13 11:12:00,2185-11-13 22:00:00,1

In [5]:
# Patient death, discharge location is DIED
patient_death_2 = f"""
--sql
SELECT
    *
FROM
    {mimic_core}.admissions AS admissions
WHERE
    admissions.discharge_location LIKE ("DIED")
ORDER BY
    subject_id, hadm_id
"""

In [6]:
run_query(patient_death_2)

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,marital_status,ethnicity,edregtime,edouttime,hospital_expire_flag
0,10001884,26184834,2131-01-07 20:39:00,2131-01-20 05:15:00,2131-01-20 05:15:00,OBSERVATION ADMIT,EMERGENCY ROOM,DIED,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,2131-01-07 13:36:00,2131-01-07 22:13:00,1
1,10002155,20345487,2131-03-09 20:33:00,2131-03-10 01:55:00,2131-03-10 21:53:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,MARRIED,WHITE,2131-03-09 19:14:00,2131-03-09 21:33:00,1
2,10003400,23559586,2137-08-04 00:07:00,2137-09-02 17:05:00,2137-09-02 17:05:00,URGENT,TRANSFER FROM HOSPITAL,DIED,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,NaT,NaT,1
3,10004401,25777141,2144-06-05 19:45:00,2144-06-18 21:30:00,2144-06-18 21:30:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,MARRIED,WHITE,2144-06-05 16:08:00,2144-06-05 20:36:00,1
4,10004720,22081550,2186-11-12 18:01:00,2186-11-17 18:30:00,2186-11-17 18:30:00,EW EMER.,INFORMATION NOT AVAILABLE,DIED,Medicare,ENGLISH,SINGLE,WHITE,2186-11-12 16:09:00,2186-11-12 19:55:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9233,19995127,27369164,2138-06-06 18:00:00,2138-06-12 01:48:00,2138-06-12 01:48:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,2138-06-06 13:56:00,2138-06-06 19:40:00,1
9234,19996061,26115327,2118-07-25 17:55:00,2118-07-29 13:00:00,2118-07-29 13:00:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,SINGLE,WHITE,2118-07-25 14:03:00,2118-07-27 00:28:00,1
9235,19998843,24842066,2187-02-05 09:27:00,2187-02-08 17:28:00,NaT,EW EMER.,EMERGENCY ROOM,DIED,Other,?,SINGLE,UNKNOWN,2187-02-05 08:44:00,2187-02-05 10:12:00,0
9236,19999297,21439025,2162-08-14 23:55:00,2162-08-23 04:16:00,2162-08-23 04:16:00,OBSERVATION ADMIT,EMERGENCY ROOM,DIED,Other,ENGLISH,SINGLE,OTHER,2162-08-14 18:26:00,2162-08-15 02:01:00,1
9237,19999840,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,2164-09-17 13:42:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,WIDOWED,WHITE,2164-09-10 11:09:00,2164-09-10 14:46:00,1

In [9]:
# Patient death, discharge location is DIED
# also in ICU
patient_death_icu = f"""
--sql
SELECT
    *
FROM
    {mimic_core}.admissions AS admissions
    INNER JOIN {mimic_icu}.icustays AS icustays
        ON admissions.hadm_id = icustays.hadm_id
WHERE
    admissions.discharge_location LIKE ("DIED")
ORDER BY
    admissions.subject_id, admissions.hadm_id, icustays.stay_id
"""

In [10]:
run_query(patient_death_icu)

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,...,edouttime,hospital_expire_flag,subject_id_1,hadm_id_1,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10001884,26184834,2131-01-07 20:39:00,2131-01-20 05:15:00,2131-01-20 05:15:00,OBSERVATION ADMIT,EMERGENCY ROOM,DIED,Medicare,ENGLISH,...,2131-01-07 22:13:00,1,10001884,26184834,37510196,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2131-01-11 04:20:05,2131-01-20 08:27:30,9.171817
1,10002155,20345487,2131-03-09 20:33:00,2131-03-10 01:55:00,2131-03-10 21:53:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,...,2131-03-09 21:33:00,1,10002155,20345487,32358465,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2131-03-09 21:33:00,2131-03-10 18:09:21,0.858576
2,10003400,23559586,2137-08-04 00:07:00,2137-09-02 17:05:00,2137-09-02 17:05:00,URGENT,TRANSFER FROM HOSPITAL,DIED,Medicare,ENGLISH,...,NaT,1,10003400,23559586,34577403,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2137-08-10 19:54:51,2137-08-13 17:54:54,2.916701
3,10003400,23559586,2137-08-04 00:07:00,2137-09-02 17:05:00,2137-09-02 17:05:00,URGENT,TRANSFER FROM HOSPITAL,DIED,Medicare,ENGLISH,...,NaT,1,10003400,23559586,38383343,Coronary Care Unit (CCU),Medical Intensive Care Unit (MICU),2137-08-17 17:36:37,2137-09-02 19:17:11,16.069838
4,10004401,25777141,2144-06-05 19:45:00,2144-06-18 21:30:00,2144-06-18 21:30:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,...,2144-06-05 20:36:00,1,10004401,25777141,39699336,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2144-06-05 20:36:00,2144-06-18 23:24:49,13.117234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8790,19992885,20352341,2152-07-17 08:03:00,2152-07-24 02:56:00,2152-07-24 22:45:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,...,2152-07-17 08:21:00,1,19992885,20352341,35180845,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2152-07-17 08:21:00,2152-07-25 02:56:14,7.774468
8791,19995127,27369164,2138-06-06 18:00:00,2138-06-12 01:48:00,2138-06-12 01:48:00,EW EMER.,EMERGENCY ROOM,DIED,Medicare,ENGLISH,...,2138-06-06 19:40:00,1,19995127,27369164,32899958,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2138-06-07 07:15:05,2138-06-09 17:44:46,2.437280
8792,19998843,24842066,2187-02-05 09:27:00,2187-02-08 17:28:00,NaT,EW EMER.,EMERGENCY ROOM,DIED,Other,?,...,2187-02-05 10:12:00,0,19998843,24842066,30988867,Trauma SICU (TSICU),Trauma SICU (TSICU),2187-02-05 10:12:00,2187-02-08 18:19:39,3.338646
8793,19999297,21439025,2162-08-14 23:55:00,2162-08-23 04:16:00,2162-08-23 04:16:00,OBSERVATION ADMIT,EMERGENCY ROOM,DIED,Other,ENGLISH,...,2162-08-15 02:01:00,1,19999297,21439025,37364566,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2162-08-16 05:48:32,2162-08-23 06:22:41,7.023715
8794,19999840,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,2164-09-17 13:42:00,EW EMER.,EMERGENCY ROOM,DIED,Other,ENGLISH,...,2164-09-10 14:46:00,1,19999840,21033226,38978960,Trauma SICU (TSICU),Surgical Intensive Care Unit (SICU),2164-09-12 09:26:28,2164-09-17 16:35:15,5.297766